# Eventual additional properties in camel case
bucketOne:
  # Supported properties are the same ones as supported by CF resource for S3 bucket
  # See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
  name: my-custom-bucket-name
  versioningConfiguration:
    Status: Enabled